services:
  - type: web
    name: smarthealth-chatbot
    env: python
    buildCommand: pip install Flask==2.3.3 Flask-CORS==4.0.0
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0 